new rectangle background
  size 640,480
  paint blue
new circle sun
  paint orange
  outline black 5
  size 200,200
  position -60,-60
new circle
  paint yellow
  size 100,50
  move 400,100
new rect ground
  paint green
  outline gray
  move 0,350
  size 1000,150
new text title
  write Ansley, I love you!!!
  paint white
  move 100,100
wait 1 second
  move 120,120
wait 1 second
  move 140,140
wait 1 second
new text melinda
  write You too, Melinda Pie.
  paint red
  move 200,200

